ep_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Shop_app urls include
    path('', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from . import views


app_name = 'Shop'

urlpatterns = [
    # Shop_app urls include
    path('', views.home_page, name='home'),
    # ------ SHOP URLS -------
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('catalog/<slug:slug>/', views.category_catalog, name='category_catalog'),
    path('search/', views.search_products, name='search_products'),
    # ------ VENDOR URLS -----
    path('vendors/', views.vendor_list, name='vendore_list'),
    path('vendor_categories/<slug:slug_vendor>/', views.vendor_category_list, name='vendor'),
    path('vendor/<slug:slug_vendore>/<slug:slug_category>/', views.vendor_product_list, name='vendor_product_list'),
]

templates/vendors/vendor_category_list.html
{% extends 'base.html' %}
{% load mptt_tags %}
{% load static %}
{% block title %}
    Купить товары [{{ vendor.name|upper }}] - сравнивайте цены, читайте отзывы
{% endblock title %}

{% block description %}
    Интересуют товары компании {{ vendor.name|upper }}? В вашем распоряжение все категории где можно сравнить цены, читать отзывы и смотреть видеообзоры.
{% endblock description %}


{% block content %}
<div class="main-content-wrapper">
    <div class="shop-area section-padding">
        <div class="container-fluid">
        <div class="section-title" id="prices">
            <h2>Все категории товаров бренда [{{ vendor.name|upper }}]</h2>
        </div>
            <div class="row">
                <div class="col-12">
                    <!-- Shop Layout Start -->
                    <div class="main-shop-wrapper">
                        <div class="product-grid-view">
                            <div class="row no-gutters d-flex justify-content-center">
                                {% for cat in categories %}
                                <div class="col-xl-2 col-lg-4 col-md-6">
                                    <!-- Product Box Start -->
                                    <a href="{% url 'shop:vendor_product_list' vendor.slug cat.slug %}">
                                    <div class="product-box variable-product">
                                        {% with cat.products.all|first as first_pro %}
                                        <div class="product-box__image">
                                            <img src="{% if cat.category_image %}{{ cat.category_image.url }}{% elif first_pro.product_image_category %}{{ first_pro.product_image_category.url }}{% else %}{% static 'images/zaglushka_cat.png' %}{% endif %}" alt="Сравнение цен на {{ cat.name }}" class="primary_image">
                                        </div>
                                        {% endwith %}
                                        <div class="product-box__footer">
                                            <div class="product-box__desc">
                                                <p class="product-box__title font-weight-bolder">{{ cat.name }}</p>
                                            </div>
                                        </div>
                                    </div>
                                    </a>
                                    <!-- Product Box End -->
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- Shop Layout End -->
                </div>
            </div>
            {% if vendor.description %}
            <div class="my-5">
                {{ vendor.description|safe}}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/vendors/vendor_list.html
{% extends 'base.html' %}


{% block title %}Выберите бренд, найдите нужный вам товар и сравнивайте цену{% endblock title %}
{% block description %}У вас есть любимый бренд? Найдите его на сайте, там все товарные категории, цены из разных интернет-магазинов, видеообзоры и отзывы на товары.{% endblock description %}

{% block content %}
<div class="main-content-wrapper">
    <div class="shop-area section-padding">
        <div class="container-fluid">
            <div class="section-title" id="prices">
                <h2>Поиск Бренда по Алфавиту</h2>
            </div>
            <div class="row">
            <form method="get" action="." id="testing">
                <div class="btn-toolbar btn-group-toggle mt--20" data-toggle="buttons">
                    {% for i in vandor_alphabet %}
                        <label class="btn alphabet btn-primary {% if request.GET.ven == i %}active{% endif %}">
                            <input type="radio"  name="ven" id="option1" autocomplete="off" value="{{ i }}" onchange="document.getElementById('testing').submit()"> {{ i }}
                        </label>
                    {% endfor %}
                </div>
                <div class="btn-toolbar btn-group-toggle mt--20" data-toggle="buttons">
                    {% for i in vendor_alphabet_rus %}
                        <label class="btn alphabet btn-primary {% if request.GET.ven == i %}active{% endif %}">
                            <input type="radio"  name="ven" id="option1" autocomplete="off" value="{{ i }}" onchange="document.getElementById('testing').submit()"> {{ i }}
                        </label>
                    {% endfor %}
                </div>
                <div class="btn-group btn-group-toggle flex-wrap mt--20" data-toggle="buttons">
                    {% for i in digits %}
                        <label class="btn alphabet btn-primary {% if request.GET.ven == i %}active{% endif %}">
                            <input type="radio"  name="ven" id="option1" autocomplete="off" value="{{ i }}" onchange="document.getElementById('testing').submit()"> {{ i }}
                        </label>
                    {% endfor %}
                </div>
            </form>
            </div>
            <div class="row mt--60">
                    {% for vendor in list_vendor %}
                        <div class="col-lg-2 col-md-3 col-sm-4 col-6 py-4 text-uppercase d-block">
                            <a href="{{ vendor.get_absolute_url }}">{{ vendor.name }}</a>
                        </div>
                    {% empty %}
                        <p class="display-4">Бренды пока отсутсвуют в базе данных</p>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>




{% endblock %}

templates/vendors/vendor_product_list.html
{% extends 'base.html' %}
{% load mptt_tags %}
{% load static %}

{% block title %}
    Сравнить цену и купить [{{ category.name }}] бренда [{{ vendor.name|upper }}]
{% endblock title %}
{% block description %}
    Вы ищите {{ category.name }} от компании {{ vendor.name|upper }} и желате купить товар по самой низкой цене. В этом разделе все товары, актуальные цены, отзывы и видео обзоры.
{% endblock description %}

{% block content %}
<div class="main-content-wrapper">
    <div class="shop-area section-padding">
        <div class="container-fluid">
        <div class="section-title" id="prices">
            <h2>"{{ category.name }}" от бренда "{{ vendor.name|upper }}"</h2>
        </div>
            <div class="main-shop-wrapper">
            <div class="product-grid-view">
                <div class="row no-gutters">
                    {% for product in list_pro %}
                    <div class="col-xl-2 col-md-6">
                                <!-- Product Box Start -->
                    <a href="{{ product.get_absolute_url }}">
                        <div class="product-box variable-product">
                            <div class="product-box__image">
                                <img src="{% if product.product_image_category %}{{ product.product_image_category.url }}{% else %}{% static 'images/zagluschka.png' %}{% endif %}" alt="{{ product.name }}" class="primary_image" height="160">
                            </div>
                            <div class="product-box__footer">
                                <div class="product-box__desc">
                                    <p class="product-box__title">{{ product.name }}</p>
                                    <p class="product-box__price">
                                        <p class="product-box__price">
                                            <span class="sale-price">от {{ product.min_price }} &#8381;</span>
                                        </p>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </a>
                        <!-- Product Box End -->
                    </div>
                    {% empty %}
                        <div>К сожалению поиск не дал результатов, попробуйте подобрать другое ключевое слово!</div>
                    {% endfor %}
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock content %}