ep_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Shop_app urls include
    path('', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from . import views


app_name = 'Shop'

urlpatterns = [
    # Shop_app urls include
    path('', views.home_page, name='home'),
    # ------ SHOP URLS -------
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('catalog/<slug:slug>/', views.category_catalog, name='category_catalog'),
    path('search/', views.search_products, name='search_products'),
    # ------ VENDOR URLS -----
    path('vendors/', views.vendor_list, name='vendore_list'),
    path('vendor_categories/<slug:slug_vendor>/', views.vendor_category_list, name='vendor'),
    path('vendor/<slug:slug_vendore>/<slug:slug_category>/', views.vendor_product_list, name='vendor_product_list'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Сравнивайте цены, читайте отзывы и пользуйтесь скидками - www.pricerace.ru{% endblock title %}</title>
    <meta name="description" content="{% block description %}Сравнение цен, скидки и отзывы на большое количество товаров Электроники, бытовой техники, всё для дома, детские товары и множество других категорий{% endblock description %}">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'assets/img/icon.png' %}">
    <!-- ************************* CSS ************************* -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- All Plugins CSS css -->
    <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- modernizr JS
    ============================================ -->
    <script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
</head>
<body>
    <!--[if lte IE 9]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->
    <!-- Main Wrapper Start -->
    <div class="wrapper">
        <!-- Header area Start -->
        <header class="header header-1">
            <div class="header-middle header-1--middle">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-3 col-sm-4">
                            <div class="header-middle__left">
                                <!-- Logo Start -->
                                <a href="{% url 'shop:home' %}" class="logo-box">
                                    <img src="assets/img/logo.png" alt="logo" class="img-fluid">
                                </a>
                                <!-- Logo End -->

                                <!-- Category Nav Start -->
                                <div class="category-nav d-lg-block d-none">
                                    <h2 class="category-nav__title" id="js-cat-nav-title"><i class="fa fa-bars display-4"></i> <span>Категории</span></h2>

                                    <ul class="category-nav__menu hidden-in-default" id="js-cat-nav">
                                    {% for cat in categories_nav %}
                                        {% if cat.is_root_node %}
                                        <li class="category-nav__menu__item has-children">
                                            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                                            <div class="category-nav__submenu">
                                                <div class="category-nav__submenu--inner">
                                                    {% for cat_child in cat.get_children %}
                                                    <ul>
                                                        <li><a href="{{ cat_child.get_absolute_url }}">{{ cat_child.name }}</a></li>
                                                    </ul>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </li>
                                        {% endif %}
                                    {% endfor %}
                                    </ul>
                                </div>
                                <!-- Category Nav End -->
                            </div>
                        </div>
                        <div class="col-xl-8 col-lg-7 order-3 order-lg-2">
                            <!-- Search Form Start -->
                            <form action="{% url 'shop:search_products' %}" method="get" class="search-form search-form--1">
                                <input type="text" name="q" class="search-form__input" placeholder="Что вы ищете?">
                                <button class="search-form__submit form-btn">
                                    <i class="fa fa-search"></i>
                                </button>
                            </form>
                            <!-- Search Form End -->
                        </div>
                        <div class="col-lg-2 col-sm-8 order-2 order-lg-3">

                            <!-- Header Cart Start -->

                            <!-- Header Cart End -->

                        </div>
                        <div class="col-12 d-lg-none order-4">
                            <!-- Category Mobile Menu Start -->
                            <div class="category-moble-menu"></div>
                            <!-- Category Mobile Menu End -->
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header area End -->

        {% block content %}
        {% endblock content %}

        <!-- Footer area Start -->
        <footer class="footer footer--1">
            <div class="footer-top">
            </div>
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-12 text-center">
                            <!-- Copyright Text Start -->
                            <p class="copyright-text">
                                &copy; Все права защищены. www.pricerace.ru
                            </p>
                            <!-- Copyright Text End -->
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer area End -->
    </div>
    <!-- Main Wrapper End -->
    <!-- Scroll To Top -->
    <a class="scroll-to-top" href=""><i class="fa fa-angle-double-up"></i></a>
    <!-- ************************* JS ************************* -->
    <!-- jQuery JS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Popper JS -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins JS -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Main JS -->
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/home_page.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Populate Area Start -->
<section class="related-product pt--30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <h2>Популярные товары</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="related-product__carousel owl-carousel js-popular-product">
                    <!-- Product Box Start -->
                    {% for prod in list_pro %}
                    <div class="product-box variable-product">
                    <a href="{{ prod.get_absolute_url }}">
                        <div class="product-box__image">
                            <img src="{% if prod.product_image_category %}{{ prod.product_image_category.url }}{% else %}{% static 'images/zagluschka.png' %}{% endif %}" alt="{{ prod.name }} - Сравнить цену, характеристики, отзывы" class="primary_image" height="160">
                        </div>
                        <div class="product-box__footer">
                            <div class="product-box__desc">
                                <p class="product-box__title">{{ prod.name|truncatechars:60 }}</p>
                                <p class="product-box__price">
                                    <span class="sale-price">от {{ prod.min_price }} &#8381;</span>
                                </p>
                            </div>
                        </div>
                    </a>
                    </div>
                    {% endfor %}
                    <!-- Product Box End -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Populate Product Area End -->

<!-- Top Categories Area Start -->
<section class="related-product pt--50">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <h2>Популярные категории</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="related-product__carousel owl-carousel js-popular-product">
                    <!-- Category Box Start -->
                    {% for cat in favorites_cat %}
                    <div class="product-box variable-product">
                    <a href="{{ cat.get_absolute_url }}">
                        <div class="product-box__image">
                            <img src="{% if product.product_image_category %}{{ product.product_image_category.url }}{% else %}{% static 'images/zagluschka.png' %}{% endif %}" alt="product image" class="primary_image" height="230">
                        </div>
                        <div class="product-box__footer">
                            <div class="product-box__desc">
                                <p class="product-box__title font-weight-bolder">{{ cat.name }}</p>
                            </div>
                        </div>
                    </a>
                    </div>
                    {% endfor %}
                    <!-- Category Box End -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Top Categories Product Area End -->

<!-- Text Area Start -->
<div class="banner-box-area section-padding">
    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-md-4 mb-sm--30">
                <div class="banner-box">
                    <h1>header 1</h1>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="banner-box">
                    <h1>header 1</h1>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="banner-box">
                    <h1>header 1</h1>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Text Area End -->
{% endblock content %}